name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker ps
      run: docker ps
    - name: docker start
      run: docker-compopse start
    - name: docke exec
      run: docker exec -it web bash
    - name: php unit
      run: php artisan test
